create table src_Comics (
	ID_Comic INT,
	Nombre VARCHAR(50),
	Autor VARCHAR(50),
	Nombre_Capitulo INT
);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (8660, 'Mat Lam Tam', 'adiprose0', 9328);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (8747, 'Aerified', 'cfletcher1', 2602);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (5726, 'Aerified', 'speterken2', 4341);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (4801, 'Ronstring', 'wswinford3', 6134);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (7488, 'Y-find', 'blumm4', 8225);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (3611, 'Trippledex', 'remerine5', 6332);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (2923, 'Voltsillam', 'omckelvie6', 9949);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (1384, 'Home Ing', 'dstredwick7', 1702);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (3696, 'Hatity', 'sdanilishin8', 7207);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (9233, 'Y-find', 'akleinfeld9', 9855);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (4090, 'Y-find', 'lgooderea', 2571);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (2398, 'Treeflex', 'kcutrissb', 1771);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (5314, 'Cookley', 'mmosedalec', 393);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (6325, 'Flowdesk', 'edommersend', 9860);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (4518, 'Voltsillam', 'clobliee', 9866);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (3474, 'Greenlam', 'awallikerf', 2748);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (6942, 'Job', 'ledisg', 3616);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (6758, 'Cookley', 'eflaggh', 6269);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (885, 'Tin', 'apimmockei', 9455);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (1376, 'Matsoft', 'wyoungej', 5815);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (1063, 'Subin', 'cvigarsk', 5564);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (8242, 'Temp', 'mpaviourl', 3676);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (4142, 'Biodex', 'zcolefordm', 1887);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (5218, 'Tres-Zap', 'jmcmychemn', 7864);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (52, 'Flowdesk', 'blegero', 253);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (9085, 'Trippledex', 'cclassenp', 866);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (4542, 'Bitchip', 'mwhithornq', 9876);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (1902, 'Lotlux', 'moxboroughr', 2410);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (3279, 'Lotlux', 'gleseks', 9975);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (5413, 'Solarbreeze', 'kbartoszewiczt', 6322);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (2941, 'Opela', 'lmcivoru', 2521);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (8848, 'Vagram', 'nansellv', 5804);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (8765, 'Hatity', 'trycraftw', 7553);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (3894, 'It', 'slittx', 8772);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (5990, 'Fixflex', 'bstoreyy', 5284);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (1015, 'Veribet', 'tpedgriftz', 5341);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (2214, 'Tresom', 'kdupre10', 4063);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (9341, 'Alphazap', 'yduckers11', 9476);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (2798, 'Lotstring', 'rjosselson12', 8604);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (3947, 'Mat Lam Tam', 'dconklin13', 6906);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (3250, 'Bitchip', 'eshellcross14', 1720);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (1345, 'Trippledex', 'gtalby15', 3128);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (1173, 'Viva', 'sloalday16', 1696);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (8343, 'Fixflex', 'tizhak17', 9103);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (5070, 'Holdlamis', 'sranscombe18', 3506);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (5949, 'Greenlam', 'dmarien19', 7706);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (5634, 'Namfix', 'pgregan1a', 3016);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (5901, 'Home Ing', 'ddugdale1b', 6737);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (6254, 'Transcof', 'nwillishire1c', 5657);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (2179, 'Cardify', 'nhughs1d', 9511);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (1358, 'Lotlux', 'efirpo1e', 5794);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (3278, 'Redhold', 'ooulett1f', 9339);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (6727, 'Flowdesk', 'kburley1g', 9848);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (8083, 'Greenlam', 'eminkin1h', 3593);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (3585, 'Trippledex', 'garno1i', 2467);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (3701, 'Vagram', 'cjellico1j', 1694);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (6608, 'Toughjoyfax', 'ldinapoli1k', 69);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (8068, 'Wrapsafe', 'swatters1l', 6184);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (5905, 'Fintone', 'ekupke1m', 6692);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (7545, 'Otcom', 'gjuden1n', 9244);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (8157, 'Quo Lux', 'hflukes1o', 2146);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (8481, 'Y-Solowarm', 'oscading1p', 4866);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (8067, 'Temp', 'imajor1q', 3287);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (8936, 'Daltfresh', 'tsantino1r', 214);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (2127, 'Cookley', 'rfrancombe1s', 9712);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (7600, 'Holdlamis', 'gvalde1t', 8791);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (1085, 'Viva', 'xbehn1u', 1476);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (4841, 'Mat Lam Tam', 'rlexa1v', 8239);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (4944, 'Fix San', 'brosendorf1w', 8970);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (4562, 'Sonsing', 'kwarlaw1x', 387);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (4790, 'Transcof', 'sainge1y', 1187);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (1771, 'Span', 'aberston1z', 6584);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (1337, 'Konklab', 'dwhittier20', 5572);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (7452, 'Y-find', 'kcottell21', 6763);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (7734, 'Prodder', 'hfuente22', 1673);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (7092, 'Biodex', 'cwallbridge23', 8976);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (19, 'Treeflex', 'lgarfield24', 618);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (1364, 'Daltfresh', 'galeksankov25', 9327);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (2967, 'Voltsillam', 'hwinders26', 7462);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (3741, 'Trippledex', 'dfellman27', 1442);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (5713, 'Konklux', 'gstorch28', 1614);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (2657, 'Sonair', 'fbangley29', 8795);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (4033, 'Zaam-Dox', 'isaleway2a', 2321);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (9967, 'Tampflex', 'lhackett2b', 54);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (5741, 'Overhold', 'jzannetti2c', 849);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (5412, 'Gembucket', 'hgronowe2d', 5988);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (2054, 'Sonsing', 'nwackly2e', 4681);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (8978, 'Wrapsafe', 'lvolett2f', 5355);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (7674, 'Y-Solowarm', 'jcalles2g', 3491);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (9056, 'Bytecard', 'cskally2h', 5147);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (6651, 'Y-find', 'rdunbobbin2i', 4114);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (1946, 'Alpha', 'dmellers2j', 335);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (3184, 'Voyatouch', 'rjaneczek2k', 1292);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (4760, 'Tresom', 'mrobbeke2l', 9829);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (1543, 'Ventosanzap', 'bheijne2m', 3076);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (9272, 'Opela', 'svandervelde2n', 1842);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (7762, 'Y-find', 'rhowey2o', 229);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (3422, 'Regrant', 'dcasswell2p', 8156);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (5241, 'Sub-Ex', 'dbrierley2q', 3159);
insert into src_Comics (ID_Comic, Nombre, Autor, Nombre_Capitulo) values (9699, 'Trippledex', 'tlerwill2r', 3610);